version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: delivery_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rupupuru@01
      POSTGRES_DB: delivery
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: delivery_redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: delivery_app
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/delivery?sslmode=disable
      REDIS_ADDR: redis:6379
      PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - ./web:/app/web
      - ./migrations:/app/migrations

volumes:
  postgres_data:
